# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rhche
type: Opaque
data:
  che-fabric8-multitenant: "true"
  che-jsonrpc-max-pool-size: "2000"
  che-keycloak-client-id: "che-public"
  che-keycloak-oidc-provider: "NULL"
  che-keycloak-realm: "che"
  che-keycloak-use-nonce: "false"
  che-limits-user-workspaces-run-count: "1"
  che.logs.dir: "/data/logs"
  che-openshift-precreate-subpaths: "false"
  che-openshift-secure-routes: "false"
  che-secure-external-urls: "false"
  che-server-java-opts: "-XX:+UseParallelGC -XX:MinHeapFreeRatio=25 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true -Xms50m -Xmx180m -Dfile.encoding=UTF8"
  che.workspace.agent.dev.inactive_stop_timeout_ms: "900000"
  che-workspace-logs: "/workspace_logs"
  che-workspace-server-ping-interval-milliseconds: "500"
  che-workspace-server-ping-success-threshold: "1"
  che-workspaces-java-opts: "-XX:+UseG1GC -XX:+UseStringDeduplication -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:MaxRAM=1200m -Xms256m"
  enable-workspaces-autostart: "false"
  infra-machine-start-timeout: "5"
  infra-pvc-strategy: "common"
  infra-trust-certs: "true"
  local-conf-dir: "/etc/conf"
  log-level: "INFO"
  multi-user: "true"
  remote-debugging-enabled: "true"
  workspaces-memory-limit: "2400"
  workspaces-memory-limit-max: "2400mb"
  workspace-storage: "/home/user/che/workspaces"
