# Copyright (c) 2012-2018 Red Hat, Inc
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
---
kind: Template
apiVersion: v1
metadata:
  name: keycloak
  labels:
    app: keycloak
  annotations:
    description: Che
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: keycloak
    labels:
      app: keycloak
  spec:
    replicas: 1
    selector:
      app: keycloak
    strategy:
      type: Recreate
    template:
      metadata:
        labels:
          app: keycloak
      spec:
        containers:
        - env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: POSTGRES_PORT_5432_TCP_ADDR
            value: postgres
          - name: POSTGRES_PORT_5432_TCP_PORT
            value: "5432"
          - name: POSTGRES_DATABASE
            value: keycloak
          - name: POSTGRES_USER
            value: keycloak
          - name: POSTGRES_PASSWORD
            value: keycloak
          - name: KEYCLOAK_USER
            value: admin
          - name: KEYCLOAK_PASSWORD
            value: admin
          - name: PROTOCOL
            value: "${PROTOCOL}"
          - name: ROUTING_SUFFIX
            value: "${ROUTING_SUFFIX}"
          - name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
            value: "${CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD}"
          - name: OPENSHIFT_IDENTITY_PROVIDER_CERTIFICATE
            valueFrom:
              secretKeyRef:
                key: ca.crt
                name: openshift-identity-provider
          image: '${IMAGE_KEYCLOAK}:${CHE_VERSION}'
          command: ["/scripts/kc_realm_user.sh"]
          imagePullPolicy: Always
          name: keycloak
          livenessProbe:
            failureThreshold: 11
            initialDelaySeconds: 80
            periodSeconds: 5
            successThreshold: 1
            tcpSocket:
              port: 8080
            timeoutSeconds: 30
          readinessProbe:
            failureThreshold: 10
            httpGet:
              path: auth/js/keycloak.js
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 3
            successThreshold: 1
            timeoutSeconds: 1
          ports:
          - containerPort: 8080
          resources:
            limits:
              memory: 1536Mi
            requests:
              memory: 1024Mi
          volumeMounts:
          - mountPath: /opt/jboss/keycloak/standalone/data
            name: keycloak-data
          - mountPath: /opt/jboss/keycloak/standalone/log
            name: keycloak-log
        restartPolicy: Always
        volumes:
        - name: keycloak-data
          persistentVolumeClaim:
            claimName: keycloak-data
        - name: keycloak-log
          persistentVolumeClaim:
            claimName: keycloak-log
    test: false
- apiVersion: v1
  kind: Service
  metadata:
    name: keycloak
    labels:
      app: keycloak
  spec:
    ports:
    - name: "5050"
      port: 5050
      targetPort: 8080
    selector:
      app: keycloak

- apiVersion: v1
  kind: Route
  metadata:
    name: keycloak
    labels:
      app: keycloak
  spec:
    port:
      targetPort: "5050"
    to:
      kind: Service
      name: keycloak
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: keycloak-data
    labels:
      app: keycloak
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: keycloak-log
    labels:
      app: keycloak
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
- apiVersion: v1
  kind: OAuthClient
  metadata:
    name: kc-client
    labels:
      app: keycloak
  secret: "openshift"
  redirectURIs:
    - "${PROTOCOL}://keycloak-${NAMESPACE}.${ROUTING_SUFFIX}/auth/realms/che/broker/openshift-v3/endpoint"
  grantMethod: prompt
- apiVersion: batch/v1
  kind: Job
  metadata:
    name: configure-keycloak
    labels:
      app: keycloak
  spec:
    parallelism: 1    
    completions: 1    
    template:         
      metadata:
        name: configure-keycloak
      spec:
        containers:
        - name: configure-keycloak
          image: ${KEYCLOAK_CONFIGURATOR_DOCKER_IMAGE}:${RH_CHE_VERSION}
          imagePullPolicy: Always
          env:
          - name: PROVIDER_BASE_URL
            value: ${PROVIDER_BASE_URL}
        restartPolicy: OnFailure    
parameters:
- name: PROTOCOL
  displayName: htpps or http protocol
  description: Protocol to be used in Che communications
  value: http
- name: ROUTING_SUFFIX
  displayName: Routing suffix of your OpenShift cluster
  description: This is the suffix appended to routes in your OpenShift cluster <route>.<project>.<routing_suffix>
- name: CHE_VERSION
  displayName: Eclipse Che version
  description: Eclipse Che version which defaults to nightly
  value: nightly
- name: IMAGE_KEYCLOAK
  displayName: Keycloak Image
  description: Keycloak Image. Defaults to docker.io/eclipse/che-keycloak
  value: eclipse/che-keycloak
- name: CHE_KEYCLOAK_ADMIN_REQUIRE_UPDATE_PASSWORD
  displayName: Require admin password update
  description: Ask for a password update after 1st login by admin user
  value: "true"
- name: NAMESPACE
  displayName: Minishift namespace 
  description: Minishift namespace used to install Keycloak
- name: PROVIDER_BASE_URL
  displayName: Openshift provider base URL 
  description: Base URL of the Openshift identity provider in Keycloak 
- name: KEYCLOAK_CONFIGURATOR_DOCKER_IMAGE
  displayName: Keycloak configurator image
  description: Keycloak configurator image for RhChe standalone
  value: quay.io/openshiftio/che-rh-che-standalone-keycloak-configurator
- name: RH_CHE_VERSION
  displayName: RhChe version
  description: RhChe version which defaults to latest
  value: latest
labels:
  app: keycloak
  template: keycloak
